### ISSUE TITLE
Tooltip wrong position

### ISSUE THREAD

**Issue by janresiak** [krispo/angular-nvd3#20]
![image](https://cloud.githubusercontent.com/assets/3851768/3595595/a6f965b4-0cb7-11e4-8d66-87eb05037329.png)

this is simple line chart
tooltips aren't displaying near mouse, but only if the chart isn't on top of the website
if the chart is on the top, everythig is ok

**Comment by ksr583** [comment]
I am having this same problem (the tooltips for a multi line chart with interactive guideline are showing way above where they should, all the way on another chart), but only with the interactiveGuideline and multi-tooltips. I checked that issue linked above from nvd3, and wrapping the chart in a div with position:relative moved the tooltip but not all the way into the right position. Anyone have any ideas here? This is really lame!

**Comment by jssolichin** [comment]
I think @arunkjn is right. I think it has to do with how nvd3 does Tooltip positioning.

Do you guys have your chart within a container which is scrolling, rather than a scrolling window? 

In line 773 of nv.d3.js, you can see that one of the things nvd3 takes into account when positioning tooltip is the page's scrollTop.

    scrollTop = window.pageYOffset

In my case, I have a div `#main-content-container` within the page that is actually scrolling, and so the position of the page is 0; as a result, the variable does not accurately reflect the page. If I replace above with 

    scrollTop = document.getElementById("main-content-container").scrollTop

the tooltip is positioned correctly.

**Comment by sumit1191** [comment]
I am using tooltip but data on tooltip is showing incorrectly . I have two bar on bar is showing correctly but other is showing wrong. i am attaching image1 and image2 . In the image1 tooltip data is showing correctly on the green bar while in image2 on blue bar showing tooltip data in incorrectly. on the blue bar should also showing X axis value as green bar but its showing 20 instead of COD maintenance.

Please suggest someone.
![image1](https://user-images.githubusercontent.com/32646675/31379135-12fa906e-adcb-11e7-9729-1a1d474c4a1e.jpg)
![image2](https://user-images.githubusercontent.com/32646675/31379136-13040cf2-adcb-11e7-8609-b944fce76d40.jpg)
