### ISSUE TITLE
How To Support RealTime Line

### ISSUE THREAD

**Issue by eastany** [krispo/angular-nvd3#21]
like this?
http://bost.ocks.org/mike/path/

**Comment by arunkumarv31** [comment]
I got this error "$digest already in progress" when I used $interval instead of setInterval. I need to change the speed of data refresh based on &lt;input type="range"&gt;. I was trying with $watch $apply. It is working fine with setInterval and $watch. Is there any disadvantage using setInterval instead of $interval.
