### ISSUE TITLE
Setting deepWatchData default to false breaks existing real time charts

### ISSUE THREAD

**Issue by gnail** [krispo/angular-nvd3#240]
Commit 115ae8170a49eb303dab04817bcf7726c5bfda96 sets deepWatchData to false by default. This breaks real-time charts like the [real-time charting example](http://plnkr.co/edit/yKFROu). Setting deepWatchData back to true in the config solves this problem.

 A minor version update shouldn't introduce a breaking change like this and it isn't really documented (pretty much *all* chart.data objects are "complex"). 

In my view there are three use cases: static charts, incremental updates and complete redraws. Static charts can be optimised like the Angular {{::var}} one-time binding to give the best performance possible. In the dynamic cases I think most would be of the incremental kind, and doing referential comparison would produce unexpected behaviour. Defaulting to referential equality would give sub-optimal result for static charts, completely break incremental updates and slightly benefit the complete redraws which I think are the minority in the use cases.

**Comment by footballencarta** [comment]
:+1: I experienced exactly this issue - I don't believe this change has been correctly communicated within documentation.

**Comment by krispo** [comment]
@gnail thanks for your review! We moved to default static charts due to some performance issues #75, #210, #225, [stackoverflow](http://stackoverflow.com/questions/32785163/nvd3-used-with-angular-nvd3-is-slooooowwwww/32791685#32791685). But it turned to be very painful for people, sorry for that.. In the new release [1.0.4] we found a way how to get around the issues, and backed to dynamic charts by default. Check the [docs](http://krispo.github.io/angular-nvd3/#/quickstart) for more detail. Thanks.
