### ISSUE TITLE
Any way to set tooltip's container? 

### ISSUE THREAD

**Issue by Kopleman** [krispo/angular-nvd3#414]
Acording to nv.d3.js tooltip's positions based on its container and utilize clientX and clientY, and directive set container to itself. Any way to changes this behaviour? Because my tooltips have wrong position when I enable `useInteractiveGuideline`

**Comment by krispo** [comment]
There is an option `chartContainer` for tooltip. According to the docs: it's 
`Parent dom element of the SVG that holds the chart. This will make the tooltip dom be created inside this container instead of on the document body.`
```js
tooltip: {
  chartContainer: document.body //default
}
```
But as I found in the source, `interactiveLayer.tooltip.chartContainer` uses `parentNode` container and couldn't be changed. So take this into account.

**Comment by Kopleman** [comment]
Thank you, btw Is there any way to force view of all added points on line chart?

**Comment by krispo** [comment]
Directive updates the charts automatically, but if you want to manually update, you can use `api`, check the docs...
```js
$scope.api.refresh(); // completely render the chart
// or
$scope.api.update(); // only update the view with data, default behaviour
```

**Comment by Kopleman** [comment]
Sorry, I havent explained well. I mean i have a linechart and it has points(sircles) on it, they are visible only when u hover over them, but i whant to show them all time

**Comment by Kopleman** [comment]
Also about my first question if i put any elemnt to tooltip prop(for example `tooltip: {chartContainer: document.body}` or `tooltip: {chartContainer: document.getElementById('content')}`) I get $rootScope:infdig error

**Comment by krispo** [comment]
As for points, change css styles:
```css
.nv-point {
  fill-opacity: 1!important;
  stroke-opacity: 1!important;
}
```
As for `chartContainer`, it's required tag name or query selector like `body`, `div`, `.some_class`, `#id`
```js
tooltip: {
  chartContainer: '#element_id'
}
```

**Comment by Kopleman** [comment]
Thank you, css trick works like a charm.
But for 'chartContainer' something goes wrong. In nv.d3.js(1.8.2) there as function `initTooltip()`(line 756). There is a expresion there - 
`var container = chartContainer ? chartContainer : document.body;` 
`chartContainer` is directive container, no matter what selector I pass to `tooltip`, or if I pass the element I have $rootScope:infdig error.
Here is my options for chart:
```javascript
{
	chart: {
		type: "lineChart",
		height: 450,
		margin: {
			top: 20,
			right: 20,
			bottom: 40,
			left: 60
		},
		tooltip: {
			chartContainer: "#content"
		},
		defined: function(d) { return d.y; },
		x: (function(d) { return d.x; }),
		y: (function(d) { return d.y; }),
		useInteractiveGuideline: true,
		xAxis: {
			axisLabel: "Package",
			tickFormat: function (d) {
				return d;
			}

		},
		yAxis: {
			axisLabel: "RSSI",
			tickFormat: function(d) {
				return d;
			},
			axisLabelDistance: 0
		}
	   
	}

}
```

**Comment by krispo** [comment]
Yes, if we use `useInteractiveGuideline: true`, the lib uses `interactiveLayer.tooltip` instead of `tooltip`. And in this case `interactiveLayer.tooltip.chartContainer` equals to `parentNode` or directive container in our case. Unfortunately, we couldn't change this behaviour and I couldn't help. But you can change the [source](https://github.com/novus/nvd3/blob/v1.8.2/src/models/lineChart.js#L414), if needed. 

 if we use `useInteractiveGuideline: false`, the lib uses `tooltip`, and `chartContainer` option should work fine
http://plnkr.co/edit/fvbTj55GVgCMFvr84ERw?p=preview

**Comment by Kopleman** [comment]
Thank you, a bit strange behavior.

**Comment by nishant95** [comment]
chartContainer is deprecated. How do we set a parent container to the tooltip now?

**Comment by vaibhavagrawal2912** [comment]
using chartContainer also I am not able to set the container as preferred and it always takes `document.body` as parent container.
