### ISSUE TITLE
Sunburst chart doesn´t allow duplicate children (nvd3 1.8.4)

### ISSUE THREAD

**Issue by avsilva** [krispo/angular-nvd3#533]
Using nvd3 version 1.8.4, when two or more nodes have exactly the same children's only one node and it's children gets drawn. With nvd3 version 1.8.1 there is no problem.

**Comment by jasonvlambert** [comment]
It's due to a change in the underlying nvd code. See here: [https://github.com/novus/nvd3/issues/1679](url). You need a unique key.

You could create a new property in your data called 'key', containing anything unique (I just used an incrementing integer) and put this in the chart options: `key: function (d){return d.key;}`

**Comment by dengue8830** [comment]
For future visitors of this problem, this is an example of how to implement that solution:

```
$scope.options = {
                    chart: {
                        type: 'sunburstChart',
                        height: 450,
                        color: d3.scale.category20c(),
                        duration: 250,
                        key:  function (d){return Math.random();} // this is the trick
                    }
                };
```
