### ISSUE TITLE
Best practice on comibining charts on same view

### ISSUE THREAD

**Issue by Julyseven2002** [krispo/angular-nvd3#97]
I need to create multiple charts on the same view. I selected two charts from krispo nvd3 and configured the options. Then, I use angular ng-controller to separate the directives both in the view and module. Is this alright or is there a better way of doing it? krispo nvd3 library do not have a sample chart that contain both charts I m interested in.

**Comment by santimacia** [comment]
good question, how can we manage different charts on the same page?

**Comment by krispo** [comment]
Check this: 
http://plnkr.co/edit/yKFROu?p=preview
http://plnkr.co/edit/qFa4UL?p=preview
http://plnkr.co/edit/jEQMch?p=preview

**Comment by ericmsmythe** [comment]
Hi Krispo,
I just came across angular and ng2 for nvd3 and I have a question for you. Thanks for your nice projects :-)
When you display multiple charts in the js/json, and they all share the same keys (but different data), is there a way to:
a) turn on and off keys so that this applies globally to all the charts?
and/or
b) have a selector to select certain keys to display on all the charts?

Best wishes
Eric
